spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: manage
    url: jdbc:postgresql://localhost:5432/SpringbootOperation
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
